/*
  Vidocracy Global Config
  DO NOT EDIT THIS FILE
  Instead, edit the user.config.js file
*/

var config = module.exports = {};

config.port = process.env.PORT || 3000;
config.googleAPIKey = process.env.GOOGLEAPIKEY;
config.url = process.env.URL;
